### PR TITLE
Add a __json__ method for Questions and rename a field

### LINKED ISSUE #385: question lacks a __json__ method

### PR DESCRIPTION
**Pull request by suchow**
Fixes #385.

### CODE REVIEW

**Comment by suchow** [comment]
@thomasmorgan While creating this, I noticed that Questions have both an `id` (inherited from `SharedMixin`) and a `question_id` property. I think we may have talked about this before, and you said that `question_id` is actually the questions *order* in the list? If so, is it okay to rename this `order`?

**Comment by thomasmorgan** [comment]
Sure, maybe "number" would better?

**Comment by suchow** [comment]
Okay, I've renamed `question_id` to `number`.

**Comment by suchow** [comment]
@thomasmorgan Feel free to merge if this looks good to you.

**Pull request merged**
