### PR TITLE
Various documentation fixes

### PR DESCRIPTION
**Pull request by jhamrick**
It should be really obvious how to install Wallace for people looking for this information after/during the workshop.

### CODE REVIEW

**Comment by jhamrick** [comment]
@suchow I've updated this PR with the various documentation things I've reported in the other issues. I think it is probably a good idea though to keep this PR open for the next day or two though so that I can add stuff to it as I come across it, rather than making a bunch of separate PRs for what are mostly small docs changes.

**Comment by jhamrick** [comment]
This should be fine to merge now I think.

**Comment by suchow** [comment]
@jhamrick Looks good! If you rebase over master I'll merge.

**Comment by suchow** [comment]
Rebased and merged via #420.

**Pull request closed without merging**
